// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYBR1uelaRS37v2TnC4S-9TC9Smq42Us4',
    appId: '1:213580800543:web:9acde1d5d683afa0cbeb2a',
    messagingSenderId: '213580800543',
    projectId: 'reservoir-startuptn',
    authDomain: 'reservoir-startuptn.firebaseapp.com',
    databaseURL: 'https://reservoir-startuptn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reservoir-startuptn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFLIucPSM0I49CpqleIjr9MMVC36aFSYU',
    appId: '1:213580800543:android:d2907a35ffe0eb62cbeb2a',
    messagingSenderId: '213580800543',
    projectId: 'reservoir-startuptn',
    databaseURL: 'https://reservoir-startuptn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reservoir-startuptn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgcc0TUYVel0qUw4HROuOvD3-q35gPDUo',
    appId: '1:213580800543:ios:4a74236f72225d41cbeb2a',
    messagingSenderId: '213580800543',
    projectId: 'reservoir-startuptn',
    databaseURL: 'https://reservoir-startuptn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reservoir-startuptn.appspot.com',
    iosBundleId: 'com.example.reservoirStartuptn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgcc0TUYVel0qUw4HROuOvD3-q35gPDUo',
    appId: '1:213580800543:ios:8ab9f74cd5af570fcbeb2a',
    messagingSenderId: '213580800543',
    projectId: 'reservoir-startuptn',
    databaseURL: 'https://reservoir-startuptn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reservoir-startuptn.appspot.com',
    iosBundleId: 'com.example.reservoirStartuptn.RunnerTests',
  );
}
