// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLWIgZ0pZ06Jbo1-l0dZ5Hhx9xhAJzg6s',
    appId: '1:570444901671:web:cbaffe3417b79a4f554d02',
    messagingSenderId: '570444901671',
    projectId: 'hydropulse-5335a',
    authDomain: 'hydropulse-5335a.firebaseapp.com',
    storageBucket: 'hydropulse-5335a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-iqrRFBv25yVaF9Kv3kdgbnJEtiyYkeo',
    appId: '1:570444901671:android:bde3d0c1ba15da9b554d02',
    messagingSenderId: '570444901671',
    projectId: 'hydropulse-5335a',
    storageBucket: 'hydropulse-5335a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyWx7XpHFKq9HYNFo-LdU0M7sf5WPTOTI',
    appId: '1:570444901671:ios:2049b567a8965006554d02',
    messagingSenderId: '570444901671',
    projectId: 'hydropulse-5335a',
    storageBucket: 'hydropulse-5335a.appspot.com',
    iosBundleId: 'com.example.reservoirStartuptn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyWx7XpHFKq9HYNFo-LdU0M7sf5WPTOTI',
    appId: '1:570444901671:ios:32b6dab615409076554d02',
    messagingSenderId: '570444901671',
    projectId: 'hydropulse-5335a',
    storageBucket: 'hydropulse-5335a.appspot.com',
    iosBundleId: 'com.example.reservoirStartuptn.RunnerTests',
  );
}
